### ISSUE TITLE
Missing info in General Erlang Guidelines (Wiki)

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/guidelines#114]
I was looking at https://github.com/inaka/guidelines/blob/master/ERLANG.md#steps-for-new-releases--version-bumps and propose the following improvements:
1. step `1.` should mention that this is not required if `vsn` is `git`,
2. step `2.` should mention the Installation instructions (for the Ruby gem) are found at https://github.com/github-changelog-generator/github-changelog-generator#installation,
3. step `2.` should mention options `-u github_project_namespace -p github_project` (I was forced, in `elvis_core`, to use `-u inaka -p elvis_core`.

From step `3.` on, I don't think those are instructions a developer external to the project will execute, so can't actually provide any improvements.

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon

**Comment by elbrujohalcon** [comment]
Yeah, I read this… Some inako (maybe myself) will eventually fix it :)
